///////////////////////////////////////////////////////////////////////
//                  DO NOT EDIT THIS FILE                            //
///////////////////////////////////////////////////////////////////////

let students = [
    {
        id: 0,
        first_name: 'Alan',
        last_name: 'Smith',
        grade: 9
    },
    {
        id: 1,
        first_name: 'John',
        last_name: 'Doe',
        grade: 10
    },
    {
        id: 2,
        first_name: 'Alice',
        last_name: 'Madness',
        grade: 18
    },
    {
        id: 3,
        first_name: 'Bob',
        last_name: 'Roberts',
        grade: 16
    },
    {
        id: 4,
        first_name: 'Esker',
        last_name: 'Feldspath',
        grade: 19
    },
    {
        id: 5,
        first_name: 'Mari',
        last_name: 'Annona',
        grade: 20
    }
]

export default class DB {
    static async getStudents() {
        return students;
    }

    static async setStudent(id, student) {
        let index = students.findIndex(s => s.id === id);
        if (index < 0) {
            throw new Error(`No student found for id ${id}`);
        }
        students[index] = {...students[index], ...student};
        console.log(`Student updated.`);
        console.log(students)
    }
}
